### ISSUE TITLE
NntpClient.Compression

### ISSUE THREAD

**Issue by dbeattie71** [keimpema/Usenet#2]
I started messing around with the calls in NntpClient.Compression.  What were your thoughts on handling the responses and decompression?

**Comment by keimpema** [comment]
I have a sort of working solution somewhere in the form of an NntpDecompressingConnection which implements INntpConnection but I was not satisfied with it because it had to read the entire response in memory using a blocking read with timeout. I didn't fit my desire to be able to process all response streaming. Also there is no single standard for compression. yEnc is used (astraweb) but also zlib deflate is used by others. I intend to look into it later. First I want to add yenc encoding en nzb upload.

**Comment by keimpema** [comment]
I added the file as a [gist](https://gist.github.com/keimpema/ec962384d5fe3eb7a5f5030353ba9e2b) if you are interested. You will need the SharpZipLib.NETStandard nuget package for this to work.

**Comment by dbeattie71** [comment]
Thanks, I'll check it out.  I was decompressing astraweb yenc with decompress in System.Compression but I upgraded the projects to NetCore 2.0.
